name: shopo_delivery
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  auth_buttons: ^3.0.0
  badges: ^3.0.2
  stream_transform: ^2.0.0
  # chat message ui design
  cached_network_image: ^3.2.0
  chat_bubbles: ^1.2.0
  carousel_slider: ^4.0.0
  # network connectivity checker
  connectivity_plus: ^3.0.3
  country_code_picker: ^3.0.0
  custom_pop_up_menu: ^1.2.3+1
  # functional programming thingies
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  # value equality
  equatable: ^2.0.3
  # for state management
  flutter_bloc: ^8.0.1
  flutter_html: ^3.0.0-alpha.3

  flutter_rating_bar: ^4.0.0
  flutter_svg: ^1.1.0
  # service locator
  #get_it: ^7.2.0
  google_fonts: ^3.0.1
  grouped_list: ^5.1.2
  # remote api call
  http: ^0.13.4
  # image picker from device
  image_picker: ^0.8.5
  intl: ^0.17.0
  pinput: ^2.2.31
  # local storage
  shared_preferences: ^2.0.13
  flutter_slidable: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.5
  # datetime to time ago
  timeago: ^3.2.2
  toggle_switch: ^2.0.1
  webview_flutter: ^3.0.4
  dotted_border: ^2.0.0+3
  expandable_page_view: ^1.0.17
  # payment
  flutter_stripe: ^3.2.0
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  flutter_credit_card: ^3.0.1
  shimmer: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.5.4
  lazy_load_scrollview: ^1.3.0
  rename: ^2.0.1
  dio: ^5.0.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

